"""empty message

Revision ID: c04055113af0
Revises: 
Create Date: 2020-03-09 09:07:08.946164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c04055113af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login', ['username'])
    op.add_column('registration', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_column('registration', 'emal')
    op.create_unique_constraint(None, 'role', ['role_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.add_column('registration', sa.Column('emal', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('registration', 'email')
    op.drop_constraint(None, 'login', type_='unique')
    # ### end Alembic commands ###
